FROM eclipse-temurin:17-jre-jammy AS runtime

WORKDIR /app

# On attend le JAR dans le contexte de build (téléchargé depuis les artefacts)
COPY microcrm-0.0.1-SNAPSHOT.jar /app/microcrm.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/microcrm.jar"]
